#!/bin/bash

if [ "$1" == "" ]; then
    echo "Must specify project configuration"
    exit 1
fi

set -x
set -e

project_config=$1
report_dir=$(python -m yq -r .project.report_dir $project_config)
project_label=$(python -m yq -r .project.label $project_config)
cfd_dir="$report_dir/$project_label"
cfd_dir="${cfd_dir/#\~/$HOME}"
csv_file="$cfd_dir/progress.csv"
first_date=$(cat $csv_file | head -2 | tail -1 | cut --delimiter="," -f 1)
last_date=$(cat $csv_file | tail -1 | cut --delimiter="," -f 1)
stop_date=$(date -I -d "$last_date + 1 day")

d=$first_date
while [ "$d" != "$stop_date" ]; do
    output_file="$cfd_dir/cfd-$d.png"
    if [ ! -f $output_file ]; then
        cfd -p "$project_config" -t $d
    fi
    d=$(date -I -d "$d + 1 day")
done

animation=$cfd_dir/cfd-anim-$last_date.gif
convert -delay 10 -loop 0 $cfd_dir/cfd-*.png $animation
mogrify -layers optimize $animation
